### ISSUE TITLE
glider failed with 'standard_init_linux.go:185: exec user process caused "exec format error"'

### ISSUE THREAD

**Issue by victorguo** [kometchtech/docker-build#16]
Hi,

I was trying to create a container from the image kometchtech/glider. But I always got the error:

`standard_init_linux.go:185: exec user process caused "exec format error"
`

Could you please help?

Thanks,
Victor

**Comment by kometchtech** [comment]
@victorguo 

Thanks for the report.
I reviewed Dockerfile and modified it to work.
cccb2f27ddf090040621d83533ab0d7a860bccb0

```
$ docker run --rm  kometchtech/glider                                                      
2020/02/23 23:43:21 strategy.go:82: [strategy] forward to remote servers in round robin mode.   
2020/02/23 23:43:21 server.go:56: [dns] listening UDP on :53   
2020/02/23 23:43:21 server.go:101: [dns-tcp] listening TCP on :53
2020/02/23 23:43:21 server.go:31: [http] listening TCP on :8080  
2020/02/23 23:43:21 mixed.go:69: [mixed] listening TCP on :8443  
2020/02/23 23:43:21 socks5.go:92: [socks5] listening TCP on :1080 
2020/02/23 23:43:21 socks5.go:165: [socks5-udp] listening UDP on :8443 
2020/02/23 23:43:21 socks5.go:165: [socks5-udp] listening UDP on :1080  
```
Would you please try again?

**Comment by victorguo** [comment]
@kometchtech Thanks for your quick response and fix! Really appreciated it.

However, it still doesn't work for me. I'm trying to run on QNAP TS453Bmini. It's an amd64 environment. I guess that's the real problem here. :(

**Comment by kometchtech** [comment]
@victorguo Thanks for the report.

Oh, it is used in amd64 environment.
Modify the following parts and rebuild.

https://github.com/kometchtech/docker-build/blob/cccb2f27ddf090040621d83533ab0d7a860bccb0/glider/Dockerfile#L7

I had limited use environment of the file generated by go build used in Dockerfile.

**Comment by kometchtech** [comment]
Once closed. Please reopen if you have any problems.
