### ISSUE TITLE
[dnsdist] Enable DoH backend support

### ISSUE THREAD

**Issue by agneevX** [kometchtech/docker-build#45]
Hello!

Currently, I get this error when I create a new DoH Server:

```text
Fatal Lua error: [string "chunk"]:11: Caught exception: Outgoing DNS over HTTPS support requested (via 'dohPath' on newServer()) but nghttp2 support is not available
```

It appears that the binary needs to be compiled with `nghttp2`.

Here's the relevant PR diff: https://github.com/PowerDNS/pdns/pull/10635/files

**Comment by kometchtech** [comment]
@agneevX 
I tried to respond with commit https://github.com/kometchtech/docker-build/commit/2dcdf56303abad824341a5a34399f60e43c64889 .
Could you please check if it works there?

**Comment by agneevX** [comment]
Thanks. I tried a simple config:

```
newServer({address="1.1.1.1:443", tls="openssl", dohPath="/dns-query"})
```

However, it's marked as `down`. No errors though regarding `nghttp2`.

**Comment by agneevX** [comment]
Weirdly enough, 8.8.8.8 works

```
newServer({address="8.8.8.8:443", tls="openssl", dohPath="/dns-query"})
```

Thanks for your help.
